In [2]:
import pandas as pd

perguntas = pd.read_csv("../../data/stackoverflow_perguntas.csv")
perguntas.sample(10)

Perguntas         Tags
3339  Bem, tentei fazer os valores em um CODE  demos...  jquery html
2032  Lá vou eu de novo. Tenho uma função onde se ef...      node.js
5276  Eu tenho um codigo que no meu backend ele reto...       jquery
3137  Estou usando o fullcalendar para um sistema on...       jquery
1407  É possivel pegar o SCRIPT de algum elemento.. ...  jquery html
1276  Estou fazendo esse programa para um trabalho d...        html 
2452  Estou trabalhando em uma aplicação Angular2 qu...      angular
4876  Desenvolvendo um sistema simples, me deparei c...      angular
1958  Estou querendo mapear as lista de perguntas e ...     angular 
4547  Estou utilizando um CODE  mas infelizmente não...       jquery

In [3]:
perguntas.shape

(5408, 2)

quantos tipos de tagas

In [5]:
tags = perguntas.Tags.unique()
tags

array(['node.js', 'jquery', 'html', 'html angular ', 'html ', 'angular',
       'angular ', 'jquery html  ', 'jquery ', 'jquery html',
       'jquery html ', 'html angular', 'angular node.js ', 'html  ',
       'jquery html angular', 'node.js ', 'html jquery', 'html jquery ',
       'jquery angular  ', 'html node.js', 'jquery  ', 'angular node.js',
       'jquery angular', 'html node.js ', 'jquery node.js ', 'angular  ',
       'jquery angular ', 'jquery html angular ', 'node.js html ',
       ' node.js', 'node.js html', 'html angular  ', 'jquery node.js',
       'angular html', 'html angular  node.js', 'jquery html node.js',
       'html angular node.js'], dtype=object)

In [6]:
len(tags)

37

In [7]:
lista_de_tags = list()
for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in lista_de_tags:
            lista_de_tags.append(tag)
        
print(lista_de_tags)

['node.js', 'jquery', 'html', 'angular']


In [8]:

node_js = list()
for linha_tag in perguntas.Tags:
    if "node.js" in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)
perguntas["node.js"] = node_js
perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node.js  
0           1  
1           1  
2           0  
3           0  
4           0  
...       ...  
5403        0  
5404        0  
5405        0  
5406        0  
5407        0  

[5408 rows x 3 columns]

In [9]:
def nova_coluna(lista_tags, dataframe, nome_tags):
    for tag in lista_tags:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)
        dataframe[tag] = coluna
nova_coluna(lista_de_tags, perguntas, "Tags")
perguntas.sample(10)

Perguntas          Tags  \
107   Olá galera estou montando um projeto web, e go...   jquery html   
4142  Tenho um site que possui o menu lateral fixo e...        jquery   
2845  Estava procurando uma forma de aplicar o scrol...  jquery html    
2704  Estou a criar uma aplicação WEB para dispositi...          html   
1214  tudo bem? estou com uma dúvida bem chata aqui ...   jquery html   
546   Galera, para ser bem direto, vou utilizar como...   jquery html   
4337  Estou utilizando o seguinte material como refe...       angular   
1559  Tenho um botão em um formulario que é responsa...   jquery html   
2250  Estou neste momento a fazer o Protótipo de uma...         html    
466   Criei um chat com nodejs e MySQL pra buscar in...      node.js    

      node.js  jquery  html  angular  
107         0       1     1        0  
4142        0       1     0        0  
2845        0       1     1        0  
2704        0       0     1        0  
1214        0       1     1        0  
546         0       1     1        0  
4337        0       0     0        1  
1559        0       1     1        0  
2250        0       0     1        0  
466         1       0     0        0

separando em treino e teste

In [12]:


from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Perguntas,
    perguntas.Tags
)

nao podemos usar tags, dado os problemas relacionados a strings

In [13]:

lista_zip_tags = list(zip(perguntas[lista_de_tags[0]],
                     perguntas[lista_de_tags[1]],
                     perguntas[lista_de_tags[2]],
                     perguntas[lista_de_tags[3]]))

perguntas["todas_tags"] = lista_zip_tags
perguntas.sample(10)

Perguntas             Tags  \
4123  Estou tentando criar um "glass pane" em JavaSc...            html    
4973  Estou criando um site utilizando CODE  com COD...           jquery   
895   Viva, Tenho 2 gráficos e queria trazer para el...            html    
1111  Galera, estou tentando enviar um XML da minha ...          angular   
4430  Existe a possibilidade de limpar o CODE  ou os...             html   
1190  Boa tarde,  Eu clonei um repositorio que usa a...  angular node.js   
2145  Quando o movimento do mouse é rápido acaba sai...            html    
1639  Preciso passar um array via POST para meu cont...           jquery   
613   Meu submenu category, transborda a página quan...            html    
1     Gostaria de fazer testes unitários no Node.js,...          node.js   

      node.js  jquery  html  angular    todas_tags  
4123        0       0     1        0  (0, 0, 1, 0)  
4973        0       1     0        0  (0, 1, 0, 0)  
895         0       0     1        0  (0, 0, 1, 0)  
1111        0       0     0        1  (0, 0, 0, 1)  
4430        0       0     1        0  (0, 0, 1, 0)  
1190        1       0     0        1  (1, 0, 0, 1)  
2145        0       0     1        0  (0, 0, 1, 0)  
1639        0       1     0        0  (0, 1, 0, 0)  
613         0       0     1        0  (0, 0, 1, 0)  
1           1       0     0        0  (1, 0, 0, 0)

In [14]:
lista_de_tags

['node.js', 'jquery', 'html', 'angular']

In [15]:
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Perguntas,
    perguntas.todas_tags,
    test_size = 0.2,
    random_state = 123
)

In [16]:
perguntas_treino

1577       array1 = [1,2,3];   array2 = ["um","dois","...
1927    Não sei se fui claro no título, mas quem é da ...
3409    Alguém sabe me dizer qual a melhor forma de re...
4606    Estou com problemas ao tentar validar campos d...
5237    Preciso copiar um valor de dentro de um CODE  ...
                              ...                        
5218    Tenho um sisteminha, para mudar o layout da pá...
4060    Como fazer alto scoll ao carregar a página?  E...
1346    Explicação:  Tenho uma CODE  pai que contém du...
3454    Estou querendo fazer um sistema onde eu iria t...
3582    Galera eu to com um problemão, ja pesquisei ba...
Name: Perguntas, Length: 4326, dtype: object

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features=5000, max_df=0.85)
vetorizar

TfidfVectorizer(max_df=0.85, max_features=5000)

In [18]:
vetorizar.fit(perguntas.Perguntas)
perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_test_tfidf = vetorizar.transform(perguntas_test)
print(perguntas_treino_tfidf.shape)
print(perguntas_test_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [21]:

from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression()
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino)

ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.

In [22]:

import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_test_array = np.asarray(list(tags_teste))

In [23]:


tags_treino_array

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       ...,
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0]])

In [24]:

type(tags_treino)

pandas.core.series.Series

In [25]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression()
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino)

ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.

In [26]:

type(tags_treino)

pandas.core.series.Series

In [27]:

import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_teste))
print(tags_treino_array)
print(type(tags_treino_array))

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]
<class 'numpy.ndarray'>


In [28]:

from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression(solver = 'lbfgs')
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)
print("Resultado {0: .2f}%".format(resultado_onevsrest*100))

Resultado  41.87%
